import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";

export interface Quotation {
  id: string;
  deal_id: string | null;
  customer_id: string | null;
  quotation_number: string;
  status: string;
  valid_until: string | null;
  notes: string | null;
  terms_conditions: string | null;
  subtotal: number;
  discount_percent: number;
  discount_amount: number;
  total_amount: number;
  created_at: string;
  updated_at: string;
  items?: QuotationItem[];
}

export interface QuotationItem {
  id: string;
  quotation_id: string;
  product_id: string | null;
  product_name: string | null;
  sku: string | null;
  quantity: number;
  unit_price: number;
  cost_price: number | null;
  discount_percent: number;
  line_total: number;
  notes: string | null;
  sort_order: number;
}

export const QUOTATION_STATUSES = [
  { value: "draft", label: "Rascunho" },
  { value: "sent", label: "Enviado" },
  { value: "approved", label: "Aprovado" },
  { value: "rejected", label: "Rejeitado" },
  { value: "expired", label: "Expirado" },
];

export function useQuotationsByDeal(dealId: string | undefined) {
  return useQuery({
    queryKey: ["quotations", "deal", dealId],
    queryFn: async () => {
      if (!dealId) return [];
      const { data, error } = await supabase
        .from("quotations")
        .select("*")
        .eq("deal_id", dealId)
        .order("created_at", { ascending: false });
      if (error) throw error;
      return data as Quotation[];
    },
    enabled: !!dealId,
  });
}

export function useQuotation(quotationId: string | undefined) {
  return useQuery({
    queryKey: ["quotation", quotationId],
    queryFn: async () => {
      if (!quotationId) return null;
      const { data, error } = await supabase
        .from("quotations")
        .select("*")
        .eq("id", quotationId)
        .maybeSingle();
      if (error) throw error;
      
      // Fetch items separately
      if (data) {
        const { data: items, error: itemsError } = await supabase
          .from("quotation_items")
          .select("*")
          .eq("quotation_id", quotationId)
          .order("sort_order", { ascending: true });
        if (itemsError) throw itemsError;
        return { ...data, items: items || [] } as Quotation;
      }
      return null;
    },
    enabled: !!quotationId,
  });
}

export function useCreateQuotation() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (data: {
      deal_id: string;
      customer_id?: string | null;
      valid_until?: string | null;
      notes?: string | null;
      terms_conditions?: string | null;
    }) => {
      const { data: quotation, error } = await supabase
        .from("quotations")
        .insert({
          deal_id: data.deal_id,
          customer_id: data.customer_id || null,
          valid_until: data.valid_until || null,
          notes: data.notes || null,
          terms_conditions: data.terms_conditions || null,
          quotation_number: "", // Will be auto-generated by trigger
        })
        .select()
        .single();
      if (error) throw error;
      return quotation;
    },
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({ queryKey: ["quotations", "deal", variables.deal_id] });
    },
  });
}

export function useCreateQuotationFromDeal() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (dealId: string) => {
      // First get the deal with items
      const { data: deal, error: dealError } = await supabase
        .from("deals")
        .select("*, deal_items(*)")
        .eq("id", dealId)
        .single();
      if (dealError) throw dealError;

      // Create quotation
      const { data: quotation, error: quotationError } = await supabase
        .from("quotations")
        .insert({
          deal_id: dealId,
          customer_id: deal.customer_id,
          quotation_number: "", // Auto-generated
          subtotal: deal.total_amount || 0,
          total_amount: deal.total_amount || 0,
        })
        .select()
        .single();
      if (quotationError) throw quotationError;

      // Copy deal items to quotation items
      if (deal.deal_items && deal.deal_items.length > 0) {
        const quotationItems = deal.deal_items.map((item: any, index: number) => ({
          quotation_id: quotation.id,
          product_id: item.product_id,
          product_name: item.product_name,
          sku: item.sku,
          quantity: item.quantity || 1,
          unit_price: item.unit_price || 0,
          cost_price: item.cost_price,
          line_total: (item.quantity || 1) * (item.unit_price || 0),
          sort_order: index,
        }));

        const { error: itemsError } = await supabase
          .from("quotation_items")
          .insert(quotationItems);
        if (itemsError) throw itemsError;
      }

      return quotation;
    },
    onSuccess: (_, dealId) => {
      queryClient.invalidateQueries({ queryKey: ["quotations", "deal", dealId] });
    },
  });
}

export function useUpdateQuotation() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({
      id,
      ...data
    }: Partial<Quotation> & { id: string }) => {
      const { data: quotation, error } = await supabase
        .from("quotations")
        .update(data)
        .eq("id", id)
        .select()
        .single();
      if (error) throw error;
      return quotation;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ["quotation", data.id] });
      queryClient.invalidateQueries({ queryKey: ["quotations", "deal", data.deal_id] });
    },
  });
}

export function useDeleteQuotation() {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ id, dealId }: { id: string; dealId: string }) => {
      const { error } = await supabase.from("quotations").delete().eq("id", id);
      if (error) throw error;
      return { id, dealId };
    },
    onSuccess: (_, variables) => {
      queryClient.invalidateQueries({ queryKey: ["quotations", "deal", variables.dealId] });
    },
  });
}
