// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hzzaoxtgyazdjvrnycux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6emFveHRneWF6ZGp2cm55Y3V4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY4NjU1NDEsImV4cCI6MjA4MjQ0MTU0MX0.i2CvlZGHt9c5hKm3VimcXPXkpVrd_ZBIXyJ5tORT0fw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});